name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  IMAGE_NAME: deploybot

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Generate build_ts variable
        id: current-time
        run: echo "::set-output name=time::$(date +'%Y-%m-%d %H:%M')"

      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          build_ts: "${{ steps.current-time.outputs.time }}"
        with:
          name: ${{ github.repository }}/${{ env.IMAGE_NAME }}
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile
          tags: latest
          buildargs: build_ts

      - name: Deploy package to digitalocean
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          passphrase: ${{ secrets.DO_PASSPHRASE }}
          key: ${{ secrets.DO_SSHPRIVATEKEY }}
          port: ${{ secrets.DO_PORT }}
          envs: GITHUB_USERNAME, GITHUB_TOKEN, IMAGE_NAME
          script: |
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            docker rmi $(docker images -q)
            docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker run -v /root/telegram.token:/app/telegram.token -dit docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest
